spring.application.name=gerenciamento-biblioteca

spring.datasource.url=jdbc:mysql://localhost/gerenciamento-biblioteca?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=admim

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

